-- MySQL Script generated by MySQL Workbench
-- Tue May 13 18:22:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`libro` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `editorial` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_libro`),
  UNIQUE INDEX `id_libro_UNIQUE` (`id_libro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`estudiante`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `biblioteca`.`estudiante` (
  `id_lector` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `carrera` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  UNIQUE INDEX `id_lector_UNIQUE` (`id_lector` ASC) VISIBLE,
  PRIMARY KEY (`id_lector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`prestamo` (
  `id_libro` INT NOT NULL,
  `id_lector` INT NOT NULL,
  `fecha_prestamo` DATE NOT NULL,
  `fecha_devolucion` DATE NOT NULL,
  `prestamo` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_libro`, `id_lector`),
  INDEX `fk_libro_has_estudiante_estudiante1_idx` (`id_lector` ASC) VISIBLE,
  INDEX `fk_libro_has_estudiante_libro1_idx` (`id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_libro_has_estudiante_libro1`
    FOREIGN KEY (`id_libro`)
    REFERENCES `biblioteca`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_has_estudiante_estudiante1`
    FOREIGN KEY (`id_lector`)
    REFERENCES `biblioteca`.`estudiante` (`id_lector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autor` (
  `id_autor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`libro_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`libro_autor` (
  `id_libro` INT NOT NULL,
  `id_autor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_libro`, `id_autor`),
  INDEX `fk_libro_has_autor_autor1_idx` (`id_autor` ASC) VISIBLE,
  INDEX `fk_libro_has_autor_libro1_idx` (`id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_libro_has_autor_libro1`
    FOREIGN KEY (`id_libro`)
    REFERENCES `biblioteca`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_has_autor_autor1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `biblioteca`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insertar datos en la tabla libro
INSERT INTO `biblioteca`.`libro` (titulo, editorial, area) VALUES
('El Quijote', 'Santillana', 'Literatura'),
('1984', 'Orwell Publishing', 'Ficción'),
('Cien Años de Soledad', 'Penguin', 'Literatura'),
('Introducción a la Programación', 'TechPress', 'Tecnología'),
('Matemáticas Avanzadas', 'EduBooks', 'Educación');

-- Insertar datos en la tabla estudiante
INSERT INTO `biblioteca`.`estudiante` (nombre, apellido, direccion, carrera, edad) VALUES
('Ana', 'Pérez', 'Calle 123', 'Ingeniería', 20),
('Luis', 'López', 'Avenida 456', 'Matemáticas', 22),
('María', 'González', 'Boulevard 789', 'Literatura', 21),
('Juan', 'Martínez', 'Diagonal 101', 'Ciencias', 23),
('Lucía', 'Ramírez', 'Ruta 112', 'Arte', 19);

-- Insertar datos en la tabla prestamo
INSERT INTO `biblioteca`.`prestamo` (id_libro, id_lector, fecha_prestamo, fecha_devolucion, prestamo) VALUES
(1, 1, '2023-01-01', '2023-01-15', b'1'),
(2, 2, '2023-02-01', '2023-02-15', b'0'),
(3, 3, '2023-03-01', '2023-03-15', b'1'),
(4, 4, '2023-04-01', '2023-04-15', b'0'),
(5, 5, '2023-05-01', '2023-05-15', b'1');

-- Insertar datos en la tabla autor
INSERT INTO `biblioteca`.`autor` (nombre, nacionalidad) VALUES
('Miguel de Cervantes', 'Española'),
('George Orwell', 'Británica'),
('Gabriel García Márquez', 'Colombiana'),
('Ada Lovelace', 'Británica'),
('Carl Friedrich Gauss', 'Alemana');

-- Insertar datos en la tabla libro_autor
INSERT INTO `biblioteca`.`libro_autor` (id_libro, id_autor) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5);

SELECT * FROM autor;

SELECT nombre, edad FROM estudiante;

SELECT * FROM estudiante WHERE carrera="Ingenieria";

SELECT * FROM autor WHERE nacionalidad = "Colombiana";

SELECT * FROM libro WHERE area = "Literatura";

SELECT * FROM libro WHERE editorial = "edubooks";

SELECT * FROM estudiante
WHERE edad > (SELECT AVG(edad) FROM estudiante);

SELECT nombre FROM estudiante WHERE apellido LIKE "G%";

SELECT nombre 
FROM autor a INNER JOIN libro_autor la
ON  a.id_autor = la.id_autor
INNER JOIN libro l
ON l.id_libro = la.id_libro
WHERE l.titulo = "El Quijote";

SELECT titulo 
FROM libro l INNER JOIN prestamo p
ON  l.id_libro = p.id_libro
INNER JOIN estudiante e
ON e.id_lector = p.id_lector
WHERE e.nombre = "Ana";

SELECT * FROM estudiante
WHERE edad IN (SELECT MIN(edad) FROM estudiante);

SELECT e.nombre 
FROM libro l INNER JOIN prestamo p
ON  l.id_libro = p.id_libro
INNER JOIN estudiante e
ON e.id_lector = p.id_lector
WHERE l.area = "Literatura";

SELECT l.titulo 
FROM autor a INNER JOIN libro_autor la
ON  a.id_autor = la.id_autor
INNER JOIN libro l
ON l.id_libro = la.id_libro
WHERE a.nombre = "George Orwell";

SELECT l.titulo
FROM libro l INNER JOIN prestamo p
ON  l.id_libro = p.id_libro
INNER JOIN estudiante e
ON e.id_lector = p.id_lector
WHERE p.fecha_devolucion = "2023-01-15";



