services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=testersqa'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=myuser'
    ports:
      - '3906:3306'
