-- MySQL Script generated by MySQL Workbench
-- Tue May 13 17:04:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente` (
  `id_cliente` INT NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_ncaimiento` DATETIME NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cliente_plan_internet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente_plan_internet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente_plan_internet` (
  `cliente_id_cliente` INT NOT NULL,
  `plan_internet_id_plan_internet` INT NOT NULL,
  PRIMARY KEY (`cliente_id_cliente`, `plan_internet_id_plan_internet`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `plan_internet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plan_internet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `plan_internet` (
  `id_plan_internet` INT NOT NULL,
  `identificacion_plan` VARCHAR(45) NOT NULL,
  `velocidad` DECIMAL(10,2) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `descuento` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_plan_internet`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Insertar en la tabla cliente
INSERT INTO cliente (id_cliente, dni, nombre, apellido, fecha_ncaimiento, provincia, ciudad) VALUES
(1, '12345678A', 'Juan', 'Pérez', '1990-05-15', 'Buenos Aires', 'CABA'),
(2, '87654321B', 'Ana', 'García', '1985-07-22', 'Córdoba', 'Córdoba'),
(3, '11223344C', 'Luis', 'Martínez', '1992-12-05', 'Santa Fe', 'Rosario');

-- Insertar en la tabla plan_internet
INSERT INTO plan_internet (id_plan_internet, identificacion_plan, velocidad, precio, descuento) VALUES
(1, 'Básico', 10.00, 20.00, 2.00),
(2, 'Avanzado', 50.00, 40.00, 5.00),
(3, 'Premium', 100.00, 70.00, 10.00);

-- Insertar en la tabla cliente_plan_internet
INSERT INTO cliente_plan_internet (cliente_id_cliente, plan_internet_id_plan_internet) VALUES
(1, 1),
(2, 2),
(3, 3);

-- ------------------------------------------------------------------------------------------------------------------------------------------------------
-- ------------------------------------------------------------ CONSULTAS -------------------------------------------------------------------------------
-- ------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM cliente;

SELECT * FROM plan_internet;

SELECT nombre, apellido FROM cliente WHERE provincia = 'Córdoba';

SELECT * FROM plan_internet ORDER BY precio DESC LIMIT 1;

SELECT AVG(velocidad) AS promedio_velocidad FROM plan_internet;

SELECT COUNT(*) AS total_clientes FROM cliente;

SELECT c.nombre, c.apellido FROM cliente c
JOIN cliente_plan_internet cpi ON c.id_cliente = cpi.cliente_id_cliente
WHERE cpi.plan_internet_id_plan_internet = 1; 

SELECT * FROM cliente ORDER BY fecha_ncaimiento DESC LIMIT 1;

SELECT * FROM plan_internet WHERE descuento > 10.00;

SELECT SUM(precio - descuento) AS total_ventas FROM plan_internet;
