package com.mercadolibre.melifrescosg9w31.unit.dtos;

import com.mercadolibre.melifrescosg9w31.dtos.ProductWarehouseDTO;
import com.mercadolibre.melifrescosg9w31.dtos.WarehouseDTO;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
class ProductWarehouseDTOTest {


@Test
void testNoArgsConstructor() {
    // When
    ProductWarehouseDTO dto = new ProductWarehouseDTO();

    // Then
    assertNotNull(dto);
    assertNull(dto.getProduct_id(), "Product ID should be null by default");
    assertNull(dto.getWarehouses(), "Warehouses list should be null by default");
}

// --- Test @AllArgsConstructor ---
@Test
void testAllArgsConstructor() {
    // Given
    Long productId = 123L;
    // Using a direct instance of WarehouseDTO here, assume it's defined elsewhere
    // or a nested class for testing purposes as shown previously
    WarehouseDTO warehouse1 = new WarehouseDTO(1, 100L); // Adjusted to match WarehouseDTO fields
    WarehouseDTO warehouse2 = new WarehouseDTO(2, 200L); // Adjusted to match WarehouseDTO fields
    List<WarehouseDTO> warehouses = Arrays.asList(warehouse1, warehouse2);

    // When
    ProductWarehouseDTO dto = new ProductWarehouseDTO(productId, warehouses);

    // Then
    assertNotNull(dto);
    assertEquals(productId, dto.getProduct_id(), "Product ID should match the constructor argument");
    assertEquals(warehouses, dto.getWarehouses(), "Warehouses list should match the constructor argument");
    assertEquals(2, dto.getWarehouses().size(), "Warehouses list size should be 2");
}

// --- Test Getters and Setters (generated by @Data) ---
@Test
void testGettersAndSetters() {
    // Given
    ProductWarehouseDTO dto = new ProductWarehouseDTO();
    Long productId = 456L;
    WarehouseDTO warehouse3 = new WarehouseDTO(3, 50L); // Adjusted to match WarehouseDTO fields
    List<WarehouseDTO> newWarehouses = Collections.singletonList(warehouse3);

    // When
    dto.setProduct_id(productId);
    dto.setWarehouses(newWarehouses);

    // Then
    assertEquals(productId, dto.getProduct_id(), "Getter for product_id should return the set value");
    assertEquals(newWarehouses, dto.getWarehouses(), "Getter for warehouses should return the set list");
    assertEquals(1, dto.getWarehouses().size(), "Warehouses list size should be 1 after setting");
}

// --- Test equals() and hashCode() (generated by @Data) ---
@Test
void testEqualsAndHashCode() {
    // Given
    Long productId1 = 1L;
    List<WarehouseDTO> warehouses1 = Arrays.asList(new WarehouseDTO(10, 100L), new WarehouseDTO(20, 200L));

    Long productId2 = 1L; // Same product ID
    List<WarehouseDTO> warehouses2 = Arrays.asList(new WarehouseDTO(10, 100L), new WarehouseDTO(20, 200L)); // Same warehouses

    Long productId3 = 2L; // Different product ID
    List<WarehouseDTO> warehouses3 = Collections.singletonList(new WarehouseDTO(30, 300L)); // Different warehouses

    // When
    ProductWarehouseDTO dto1 = new ProductWarehouseDTO(productId1, warehouses1);
    ProductWarehouseDTO dto2 = new ProductWarehouseDTO(productId2, warehouses2); // Should be equal to dto1
    ProductWarehouseDTO dto3 = new ProductWarehouseDTO(productId3, warehouses3); // Should be different from dto1

    ProductWarehouseDTO dto4 = new ProductWarehouseDTO(productId1, null);
    ProductWarehouseDTO dto5 = new ProductWarehouseDTO(productId1, null); // Should be equal to dto4

    // Then - equals()
    assertEquals(dto1, dto2, "dto1 and dto2 should be equal");
    assertEquals(dto2, dto1, "equals() should be symmetric");
    assertNotEquals(dto1, dto3, "dto1 and dto3 should not be equal");
    assertNotEquals(null, dto1, "Should not be equal to null");
    assertNotEquals(dto1, new Object(), "Should not be equal to a different class instance");
    assertEquals(dto4, dto5, "DTOs with null lists should be equal if other fields match");

    // Then - hashCode()
    assertEquals(dto1.hashCode(), dto2.hashCode(), "Hash codes should be equal for equal objects");
    assertNotEquals(dto1.hashCode(), dto3.hashCode(), "Hash codes should not be equal for unequal objects");
    assertEquals(dto4.hashCode(), dto5.hashCode(), "Hash codes should be equal for equal objects with null lists");
}

// --- Test toString() (generated by @Data) ---
@Test
void testToString() {
    // Given
    Long productId = 789L;
    WarehouseDTO warehouseA = new WarehouseDTO(90, 900L); // Adjusted to match WarehouseDTO fields
    List<WarehouseDTO> warehouses = Collections.singletonList(warehouseA);
    ProductWarehouseDTO dto = new ProductWarehouseDTO(productId, warehouses);

    // When
    String toStringResult = dto.toString();

    // Then
    assertNotNull(toStringResult);
    assertTrue(toStringResult.contains("product_id=" + productId), "toString() should contain product_id");
    assertTrue(toStringResult.contains("warehouses=" + warehouses), "toString() should contain warehouses list");
    assertTrue(toStringResult.contains("ProductWarehouseDTO"), "toString() should contain class name");
}}