package com.mercadolibre.melifrescosg9w31.unit.dtos;

import com.mercadolibre.melifrescosg9w31.dtos.WarehouseDTO;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class WarehouseDTOTest {

    // --- Test @NoArgsConstructor ---
    @Test
    void testNoArgsConstructor() {
        // When
        WarehouseDTO dto = new WarehouseDTO();

        // Then
        assertNotNull(dto);
        assertNull(dto.getCode(), "Code should be null by default");
        assertNull(dto.getTotalQuantity(), "Total quantity should be null by default");
    }

    // --- Test @AllArgsConstructor ---
    @Test
    void testAllArgsConstructor() {
        // Given
        Integer code = 1;
        Long totalQuantity = 100L;

        // When
        WarehouseDTO dto = new WarehouseDTO(code, totalQuantity);

        // Then
        assertNotNull(dto);
        assertEquals(code, dto.getCode(), "Code should match the constructor argument");
        assertEquals(totalQuantity, dto.getTotalQuantity(), "Total quantity should match the constructor argument");
    }

    // --- Test Getters and Setters (generated by @Data) ---
    @Test
    void testGettersAndSetters() {
        // Given
        WarehouseDTO dto = new WarehouseDTO();
        Integer newCode = 2;
        Long newTotalQuantity = 250L;

        // When
        dto.setCode(newCode);
        dto.setTotalQuantity(newTotalQuantity);

        // Then
        assertEquals(newCode, dto.getCode(), "Getter for code should return the set value");
        assertEquals(newTotalQuantity, dto.getTotalQuantity(), "Getter for totalQuantity should return the set value");
    }

    // --- Test equals() and hashCode() (generated by @Data) ---
    @Test
    void testEqualsAndHashCode() {
        // Given
        Integer code1 = 10;
        Long quantity1 = 500L;

        Integer code2 = 10; // Same code
        Long quantity2 = 500L; // Same quantity

        Integer code3 = 20; // Different code
        Long quantity3 = 500L; // Same quantity

        Integer code4 = 10; // Same code
        Long quantity4 = 600L; // Different quantity

        // When
        WarehouseDTO dto1 = new WarehouseDTO(code1, quantity1);
        WarehouseDTO dto2 = new WarehouseDTO(code2, quantity2); // Should be equal to dto1
        WarehouseDTO dto3 = new WarehouseDTO(code3, quantity3); // Should be different from dto1
        WarehouseDTO dto4 = new WarehouseDTO(code4, quantity4); // Should be different from dto1

        WarehouseDTO dtoWithNullCode = new WarehouseDTO(null, quantity1);
        WarehouseDTO anotherDtoWithNullCode = new WarehouseDTO(null, quantity1); // Should be equal

        WarehouseDTO dtoWithNullQuantity = new WarehouseDTO(code1, null);
        WarehouseDTO anotherDtoWithNullQuantity = new WarehouseDTO(code1, null); // Should be equal

        // Then - equals()
        assertEquals(dto1, dto2, "dto1 and dto2 should be equal");
        assertEquals(dto2, dto1, "equals() should be symmetric");
        assertNotEquals(dto1, dto3, "dto1 and dto3 should not be equal due to code");
        assertNotEquals(dto1, dto4, "dto1 and dto4 should not be equal due to quantity");
        assertNotEquals(null, dto1, "Should not be equal to null");
        assertNotEquals(dto1, new Object(), "Should not be equal to a different class instance");

        assertEquals(dtoWithNullCode, anotherDtoWithNullCode, "DTOs with null code should be equal if other fields match");
        assertEquals(dtoWithNullQuantity, anotherDtoWithNullQuantity, "DTOs with null quantity should be equal if other fields match");
        assertNotEquals(dto1, dtoWithNullCode, "DTOs should not be equal if one has null and other has value");

        // Then - hashCode()
        assertEquals(dto1.hashCode(), dto2.hashCode(), "Hash codes should be equal for equal objects");
        assertNotEquals(dto1.hashCode(), dto3.hashCode(), "Hash codes should not be equal for unequal objects");
        assertNotEquals(dto1.hashCode(), dto4.hashCode(), "Hash codes should not be equal for unequal objects");
        assertEquals(dtoWithNullCode.hashCode(), anotherDtoWithNullCode.hashCode(), "Hash codes should be equal for equal objects with null fields");
    }

    // --- Test toString() (generated by @Data) ---
    @Test
    void testToString() {
        // Given
        Integer code = 3;
        Long totalQuantity = 75L;
        WarehouseDTO dto = new WarehouseDTO(code, totalQuantity);

        // When
        String toStringResult = dto.toString();

        // Then
        assertNotNull(toStringResult);
        assertTrue(toStringResult.contains("code=" + code), "toString() should contain code");
        assertTrue(toStringResult.contains("totalQuantity=" + totalQuantity), "toString() should contain totalQuantity");
        assertTrue(toStringResult.contains("WarehouseDTO"), "toString() should contain class name");
    }
}