spring.application.name=ejercicio_empleados


spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=1000
spring.elasticsearch.socket-timeout=30000

spring.elasticsearch.restclient.sniffer.interval=300000
spring.elasticsearch.restclient.sniffer.delay-after-failure=30000
spring.data.elasticsearch.repositories.enabled=true
spring.data.elasticsearch.auto-create-index=true

spring.elasticsearch.verification-mode=none
spring.elasticsearch.password=
spring.elasticsearch.username=