spring.application.name=PracticaApiObrasLiterarias
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=1000
spring.elasticsearch.socket-timeout=30s

spring.elasticsearch.username=elastic
spring.elasticsearch.password=sogDkYWz
spring.data.elasticsearch.repositories.enabled=true


