# Default properties file
spring:
  jpa:
    open-in-view: false
  profiles:
    active: ${SCOPE_SUFFIX} # Comma-separated list of active profiles. Can be overridden by a command line switch.
  mvc:
    throw-exception-if-no-handler-found: true # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request.
  web:
    resources:
      add-mappings: false
  threads:
    virtual:
      enabled: true

server:
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.

springdoc:
  packages-to-scan: com.mercadolibre.melifrescosg9w31.controller
  show-actuator: true
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true

app:
  title: meli-frescos-g9-w31
  description: '@project.description@'
  version: '@project.version@'

jwt.secret: "2bd6b31a06e1db686c105b9e223e253b99497360a217a7a0f4039734c9ebcd2e"