spring.application.name=PracticaConsultasHql
spring.data.jdbc.dialect=mysql
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.url=jdbc:mysql://localhost:3306/testdbconsultashql
