# URL de conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/movies_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=movies_user
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
# update permite a Hibernate actualizar la estructura de la BD según las entidades; en producción se debe usar validate o None
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Mostrar las sentencias SQL (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true