spring.application.name=ObrasLiterariasES
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Elasticsearch Configuration
spring.elasticsearch.uris=localhost:9200
spring.elasticsearch.connection-timeout=1000
spring.elasticsearch.socket-timeout=1000

# Additional Elasticsearch Configuration
spring.elasticsearch.restclient.sniffer.interval=300000
spring.elasticsearch.restclient.sniffer.delay.after.failure=300000
spring.data.elasticsearch.repositories.enabled=true
spring.data.elasticsearch.auto.create.index=true

# Configuración específica para Elasticsearch 8.x
spring.elasticsearch.ssl.verification.mode=null
spring.elasticsearch.username=
spring.elasticsearch.password=