spring.application.name=obrasliterarias
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=O4Uss2MW
spring.data.elasticsearch.repositories.enabled=true
spring.datasource.url=
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration