-- MySQL Script generated by MySQL Workbench
-- Tue May 13 16:37:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `autor` (
  `id_autor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiante` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `estudiante` (
  `id_lector` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `carrera` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lector`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `libro` (
  `id_libro` INT NOT NULL,
  `titulo` VARCHAR(20) NOT NULL,
  `editorial` VARCHAR(20) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_libro`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `libro_autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libro_autor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `libro_autor` (
  `libro_id_libro` INT NOT NULL,
  `autor_id_autor` INT NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prestamo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `prestamo` (
  `libro_id_libro` INT NOT NULL,
  `estudiante_id_lector` INT NOT NULL,
  `fecha_pestamo` DATETIME NOT NULL,
  `fecha_devolucion` DATETIME NOT NULL,
  `devuelto` TINYINT(2) NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Insertar en la tabla autor
INSERT INTO autor (id_autor, nombre, nacionalidad) VALUES
(1, 'Autor Uno', 'Nacionalidad Uno'),
(2, 'Autor Dos', 'Nacionalidad Dos'),
(3, 'Autor Tres', 'Nacionalidad Tres'),
(4, 'Autor Cuatro', 'Nacionalidad Cuatro'),
(5, 'Autor Cinco', 'Nacionalidad Cinco');

-- Insertar en la tabla estudiante
INSERT INTO estudiante (id_lector, nombre, apellido, direccion, carrera, edad) VALUES
(1, 'Estudiante Uno', 'Apellido Uno', 'Direccion Uno', 'Carrera Uno', 20),
(2, 'Estudiante Dos', 'Apellido Dos', 'Direccion Dos', 'Carrera Dos', 21),
(3, 'Estudiante Tres', 'Apellido Tres', 'Direccion Tres', 'Carrera Tres', 22),
(4, 'Estudiante Cuatro', 'Apellido Cuatro', 'Direccion Cuatro', 'Carrera Cuatro', 23),
(5, 'Estudiante Cinco', 'Apellido Cinco', 'Direccion Cinco', 'Carrera Cinco', 24);

-- Insertar en la tabla libro
INSERT INTO libro (id_libro, titulo, editorial, area) VALUES
(1, 'Libro Uno', 'Editorial Uno', 'Area Uno'),
(2, 'Libro Dos', 'Editorial Dos', 'Area Dos'),
(3, 'Libro Tres', 'Editorial Tres', 'Area Tres'),
(4, 'El Universo', 'Editorial Cuatro', 'Area Cuatro'),
(5, 'Libro Cinco', 'Editorial Cinco', 'Internet');

-- Insertar en la tabla libro_autor
INSERT INTO libro_autor (libro_id_libro, autor_id_autor) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5);

-- Insertar en la tabla prestamo
INSERT INTO prestamo (libro_id_libro, estudiante_id_lector, fecha_pestamo, fecha_devolucion, devuelto) VALUES
(1, 1, NOW(), NOW(), 0),
(2, 2, NOW(), NOW(), 1),
(3, 3, NOW(), NOW(), 0),
(4, 4, NOW(), NOW(), 1),
(5, 5, NOW(), NOW(), 0);


SELECT * FROM estudiante WHERE edad > (SELECT AVG(edad) FROM estudiante);

SELECT autor.nombre
FROM autor
JOIN libro_autor ON autor.id_autor = libro_autor.autor_id_autor
JOIN libro ON libro.id_libro = libro_autor.libro_id_libro
WHERE libro.titulo = 'El Universo';

SELECT titulo FROM libro WHERE area <> 'Internet';
